spring:
  datasource:
#    url: ${DATABASE_URL}
#    password: ${PGPASSWORD}
#    username: ${PGUSER}
   # url: postgresql://${{ PGUSER }}:${{ PGPASSWORD }}@${{ PGHOST }}:${{ PGPORT }}/${{ PGDATABASE }}
    url: jdbc:postgresql://containers-us-west-101.railway.app:5997/railway
    password: hj7dYYPry7orCflzFDL3
    username: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ${PARAM}

#server:
#  port: ${PORT}
app:
  jwtSecret: ${KEY}