spring:
  datasource:
    url: ${DATABASE_URL}
#    password: ${PGPASSWORD}
#    username: ${PGUSER}
    driver-class-name: org.postgresql.Driver

#  jpa:
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: validate
#    properties:
#      hibernate:
#        jdbc:
#          lob:
#            non_contextual_creation: true
  mvc:
    pathmatch:
      matching-strategy: ${PARAM}

#server:
#  port: ${PORT}
app:
  jwtSecret: ${KEY}